settings:
  title: 'Anzupop Infrastructure Status'
  url: 'https://status-page.anzupop.workers.dev' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: www-anzupop-com
    name: Anzupop Home
    url: 'https://www.anzupop.com/'
    method: GET
    expectStatus: 200
    
  - id: blog-anzupop-com
    name: The Anzupop Blog
    url: 'https://blog.anzupop.com/'
    method: GET
    expectStatus: 200

  - id: navidrome-anzupop-com
    name: Anzupop Navidrome (cloudflared)
    url: 'https://navidrome-cf.anzupop.com/'
    method: GET
    expectStatus: 200

  - id: home-assistant-anzupop-com
    name: Nemo's home assistant (cloudflared)
    url: 'https://home-assistant-cf.anzupop.com/'
    method: GET
    expectStatus: 200

  - id: cernet2-entry
    name: CERNET2 Entry
    url: 'http://202.120.163.159:65443/'
    method: GET
    expectStatus: 400
